In [70]:
import cv2 as cv
import numpy as np

In [71]:
path = "OpenCV.png"
src  = cv.imread(path)

In [72]:
src.shape

(600, 487, 3)

In [73]:
gray = cv.cvtColor(src, cv.COLOR_BGR2GRAY)
cv.imshow("gray", gray)
cv.waitKey(1000)
cv.destroyAllWindows()
gray.shape

(600, 487)

In [74]:
print(gray)

[[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]


In [75]:
#ondalik yapmamiz lazim normallestirme icin;
gray = np.float32(gray)
print(gray)

[[255. 255. 255. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]
 ...
 [255. 255. 255. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]]


In [76]:
min_value, max_value, min_loc, max_loc = cv.minMaxLoc(gray)
print(min_value, max_value, min_loc, max_loc)

0.0 255.0 (42, 477) (0, 0)


In [77]:
means, stddev = cv.meanStdDev(gray)
print(means, stddev)

[[188.51469199]] [[94.02781949]]


In [78]:
dst = np.zeros(gray.shape, dtype=np.float32) # ayni boyutta 0'lar matrisi

cv.normalize(gray, dst=dst, alpha=0, beta=1.0, norm_type=cv.NORM_MINMAX)

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]], dtype=float32)

In [79]:
dst[10]

array([1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.     

In [80]:
print(np.uint8(dst*255))

[[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]


In [81]:
means, stddev = cv.meanStdDev(np.uint8(dst*255))
print(means,stddev)

[[188.51469199]] [[94.02781949]]


In [82]:
cv.imshow("NORM_MINMAX", dst)
cv.waitKey(2000)
cv.destroyAllWindows()

In [83]:
min_value, max_value, min_loc, max_loc = cv.minMaxLoc(dst)
print(min_value, max_value, min_loc, max_loc)

means, stddev = cv.meanStdDev(dst)
print(means,stddev)

0.0 1.0 (42, 477) (0, 0)
[[0.73927331]] [[0.36873654]]


In [84]:
cv.imshow("NORM_MINMAX", np.uint8(dst*255))
cv.waitKey(2000)
cv.destroyAllWindows()

Diğer normalizasyon yöntemleri;

In [85]:
dst = np.zeros(gray.shape, dtype=np.float32) # ayni boyutta 0'lar matrisi
cv.normalize(gray, dst=dst, alpha=1.0, beta=0, norm_type=cv.NORM_INF)
print(dst)
cv.imshow("NORM_INF", np.uint8(dst*255))
cv.waitKey(2000)
cv.destroyAllWindows()

[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]


In [86]:
dst = np.zeros(gray.shape, dtype=np.float32) # ayni boyutta 0'lar matrisi
cv.normalize(gray, dst=dst, alpha=1.0, beta=0, norm_type=cv.NORM_L1)
print(dst)
cv.imshow("NORM_L1", np.uint8(dst*10000000))
cv.waitKey(2000)
cv.destroyAllWindows()

[[4.6292944e-06 4.6292944e-06 4.6292944e-06 ... 4.6292944e-06
  4.6292944e-06 4.6292944e-06]
 [4.6292944e-06 4.6292944e-06 4.6292944e-06 ... 4.6292944e-06
  4.6292944e-06 4.6292944e-06]
 [4.6292944e-06 4.6292944e-06 4.6292944e-06 ... 4.6292944e-06
  4.6292944e-06 4.6292944e-06]
 ...
 [4.6292944e-06 4.6292944e-06 4.6292944e-06 ... 4.6292944e-06
  4.6292944e-06 4.6292944e-06]
 [4.6292944e-06 4.6292944e-06 4.6292944e-06 ... 4.6292944e-06
  4.6292944e-06 4.6292944e-06]
 [4.6292944e-06 4.6292944e-06 4.6292944e-06 ... 4.6292944e-06
  4.6292944e-06 4.6292944e-06]]


In [87]:
dst = np.zeros(gray.shape, dtype=np.float32) # ayni boyutta 0'lar matrisi
cv.normalize(gray, dst=dst, alpha=1.0, beta=0, norm_type=cv.NORM_L2)
print(dst)
cv.imshow("NORM_L2", np.uint8(dst*10000))
cv.waitKey(2000)
cv.destroyAllWindows()

[[0.00223929 0.00223929 0.00223929 ... 0.00223929 0.00223929 0.00223929]
 [0.00223929 0.00223929 0.00223929 ... 0.00223929 0.00223929 0.00223929]
 [0.00223929 0.00223929 0.00223929 ... 0.00223929 0.00223929 0.00223929]
 ...
 [0.00223929 0.00223929 0.00223929 ... 0.00223929 0.00223929 0.00223929]
 [0.00223929 0.00223929 0.00223929 ... 0.00223929 0.00223929 0.00223929]
 [0.00223929 0.00223929 0.00223929 ... 0.00223929 0.00223929 0.00223929]]
