In [74]:
import numpy as np
import cv2 as cv

In [75]:
src = cv.imread("geometry.png")

In [76]:
def process(image):
    gray = cv.cvtColor(image, cv.COLOR_BGR2GRAY)
    corners = cv.goodFeaturesToTrack(gray, 
                                     maxCorners=35,     # Tespit edilecek maksimum köşe sayısı.
                                     qualityLevel=0.05, # en iyi köşeye göre %5 oranında kalitede olan köşelerin kabul edileceği anlamına gelir.
                                     minDistance=10)    # Tespit edilen köşeler arasındaki minimum mesafedir. Eğer iki köşe birbirine çok yakınsa, algoritma sadece birini seçer. 
    for pt in corners:
        print(pt)
        b = np.random.randint(0, 256)
        g = np.random.randint(0, 256)
        r = np.random.randint(0, 256)
        x = np.int32(pt[0][0])
        y = np.int32(pt[0][1])
        cv.circle(image,
                  (x,y),
                  5,
                  (int(b), int(g), int(r)),
                  2)
    return image

In [77]:
shi_thomas_detection = process(src.copy())

[[203. 193.]]
[[162. 223.]]
[[277. 119.]]
[[ 32. 127.]]
[[204. 221.]]
[[286. 248.]]
[[ 58. 200.]]
[[180. 184.]]
[[167. 196.]]
[[ 15. 278.]]
[[201. 132.]]
[[238. 172.]]
[[249. 267.]]
[[ 75. 277.]]
[[243. 104.]]
[[179.  87.]]
[[ 13. 187.]]
[[ 92. 276.]]
[[140. 244.]]
[[ 33. 231.]]
[[138. 275.]]
[[227. 259.]]
[[103. 105.]]
[[236. 218.]]
[[ 80. 147.]]
[[104. 177.]]
[[111. 289.]]
[[ 32. 202.]]
[[ 58. 225.]]
[[164. 248.]]
[[186. 255.]]
[[226. 281.]]
[[180. 104.]]
[[191. 206.]]
[[120. 231.]]


In [78]:
# 2 sonucu yanyana gösterme
h, w = src.shape[:2]
result = np.zeros([h, w*2, 3], dtype=src.dtype)
result[0:h, 0:w  , :] = src
result[0:h, w:w*2, :] = shi_thomas_detection

In [79]:
cv.imshow("result",result)
cv.imwrite("result1.png",result)
cv.waitKey(0)
cv.destroyAllWindows()

![](result1.png)

![](result2.png)