 Shi thomas yöntemini hassaslaştırır.

In [46]:
import cv2 as cv
import numpy as np

In [47]:
src = cv.imread("geometry.png")

In [48]:
def process(image):
    # Shi-Thomas start
    gray = cv.cvtColor(image, cv.COLOR_BGR2GRAY)
    corners = cv.goodFeaturesToTrack(gray, 
                                     maxCorners=35,     # Tespit edilecek maksimum köşe sayısı.
                                     qualityLevel=0.05, # en iyi köşeye göre %5 oranında kalitede olan köşelerin kabul edileceği anlamına gelir.
                                     minDistance=10)    # Tespit edilen köşeler arasındaki minimum mesafedir. Eğer iki köşe birbirine çok yakınsa, algoritma sadece birini seçer. 
    
    print(len(corners))
    corners = np.float32(corners)

    for pt in corners:
        print(pt)                       # Köşe koordinatlarını yazdırır.
        b = np.random.randint(0, 256)
        g = np.random.randint(0, 256)
        r = np.random.randint(0, 256)
        x = np.int32(pt[0][0])
        y = np.int32(pt[0][1])
        cv.circle(image,
                  (x,y),
                  5,
                  (int(b), int(g), int(r)),
                  2)
    # Shi-Thomas end

    winSize  = (3 , 3)  # Köşe iyileştirme için kullanılan penceresinin boyutu (3x3).
    zeroZone = (-1, -1) # Bu parametre, pencerede merkez bölgesinde iyileştirme yaparken sıfır bölge oluşturulmasını sağlar (-1, -1: sıfır bölge yok).
    
    criteria = (cv.TermCriteria_EPS + cv.TermCriteria_COUNT, # Hata veya iterasyon sayısına göre sonlanma kriterleri.
                400,                                          # Maksimum iterasyon sayısı 40.
                0.001)                                       # Hata toleransı; köşe iyileştirme işlemi bu hata değeri altına indiğinde durur.
    corners  = cv.cornerSubPix(gray,
                               corners,     # Köşe noktaları
                               winSize,     # Pencere boyutu
                               zeroZone,    # Sıfır bölge
                               criteria)    # İyileştirme sonlanma kriterleri
    
    # Hassaslaştırılmış köşelerin koordinatlarını ekrana yazdırır
    for i in range(corners.shape[0]):
        print(" -- Refined Corner [", i, "] (", corners[i, 0, 0], ",", corners[i, 0, 1], ")")
    return image


In [49]:
sub_pixel_detection = process(src.copy())

35
[[203. 193.]]
[[162. 223.]]
[[277. 119.]]
[[ 32. 127.]]
[[204. 221.]]
[[286. 248.]]
[[ 58. 200.]]
[[180. 184.]]
[[167. 196.]]
[[ 15. 278.]]
[[201. 132.]]
[[238. 172.]]
[[249. 267.]]
[[ 75. 277.]]
[[243. 104.]]
[[179.  87.]]
[[ 13. 187.]]
[[ 92. 276.]]
[[140. 244.]]
[[ 33. 231.]]
[[138. 275.]]
[[227. 259.]]
[[103. 105.]]
[[236. 218.]]
[[ 80. 147.]]
[[104. 177.]]
[[111. 289.]]
[[ 32. 202.]]
[[ 58. 225.]]
[[164. 248.]]
[[186. 255.]]
[[226. 281.]]
[[180. 104.]]
[[191. 206.]]
[[120. 231.]]
 -- Refined Corner [ 0 ] ( 203.94954 , 191.48096 )
 -- Refined Corner [ 1 ] ( 163.07515 , 221.08556 )
 -- Refined Corner [ 2 ] ( 278.5129 , 117.66606 )
 -- Refined Corner [ 3 ] ( 30.251785 , 125.67698 )
 -- Refined Corner [ 4 ] ( 204.11906 , 219.67632 )
 -- Refined Corner [ 5 ] ( 286.0 , 248.0 )
 -- Refined Corner [ 6 ] ( 58.472374 , 199.08107 )
 -- Refined Corner [ 7 ] ( 179.06357 , 183.16353 )
 -- Refined Corner [ 8 ] ( 164.55482 , 194.82545 )
 -- Refined Corner [ 9 ] ( 14.30372 , 276.06204 )
 -- Ref

In [50]:
# 2 sonucu yanyana gösterme
h, w = src.shape[:2]
result = np.zeros([h, w*2, 3], dtype=src.dtype)
result[0:h, 0:w  , :] = src
result[0:h, w:w*2, :] = sub_pixel_detection

In [51]:
cv.imshow("result",result)
cv.imwrite("result1.png",result)
cv.waitKey(0)
cv.destroyAllWindows()

![](result1.png)