In [1]:
import cv2 as cv
import numpy as np

In [2]:
# Göreceli yol ile dosyalara erişim
path      = "../00_external_models/GOOGLENET/models"

#video_path = "../04_VIDEO_ANALYSIS_BACKGROUND_SUBTRACTION_AND_ROI_EXTRACTION_OF_THE_FOREGROUND/pedestrian.mp4"

bin_model = "../00_external_models/GOOGLENET/models/bvlc_googlenet.caffemodel"
protxt    = "../00_external_models/GOOGLENET/models/deploy.prototxt"

In [3]:
net = cv.dnn.readNet(bin_model, protxt)
layer_names = net.getLayerNames()

for name in layer_names:
    id = net.getLayerId(name)
    layer = net.getLayer(id)
    print("layer id : %d, type : %s, name : %s" % (id, layer.type, layer.name))

layer id : 1, type : Convolution, name : conv1/7x7_s2
layer id : 2, type : ReLU, name : conv1/relu_7x7
layer id : 3, type : Pooling, name : pool1/3x3_s2
layer id : 4, type : LRN, name : pool1/norm1
layer id : 5, type : Convolution, name : conv2/3x3_reduce
layer id : 6, type : ReLU, name : conv2/relu_3x3_reduce
layer id : 7, type : Convolution, name : conv2/3x3
layer id : 8, type : ReLU, name : conv2/relu_3x3
layer id : 9, type : LRN, name : conv2/norm2
layer id : 10, type : Pooling, name : pool2/3x3_s2
layer id : 11, type : Convolution, name : inception_3a/1x1
layer id : 12, type : ReLU, name : inception_3a/relu_1x1
layer id : 13, type : Convolution, name : inception_3a/3x3_reduce
layer id : 14, type : ReLU, name : inception_3a/relu_3x3_reduce
layer id : 15, type : Convolution, name : inception_3a/3x3
layer id : 16, type : ReLU, name : inception_3a/relu_3x3
layer id : 17, type : Convolution, name : inception_3a/5x5_reduce
layer id : 18, type : ReLU, name : inception_3a/relu_5x5_reduce


---

# GOOGLE NET MODELİ İLE GÖRÜNTÜ SINIFLANDIRMA

---

In [4]:
with open("../00_external_models/GOOGLENET/models/classification_classes_ILSVRC2012.txt", 'rt') as f:
    classes = f.read().split('\n')

In [5]:
classes[:5]

['tench, Tinca tinca',
 'goldfish, Carassius auratus',
 'great white shark, white shark, man-eater, man-eating shark, Carcharodon carcharias',
 'tiger shark, Galeocerdo cuvieri',
 'hammerhead, hammerhead shark']

In [6]:
net = cv.dnn.readNetFromCaffe(protxt, bin_model)

In [7]:
# nesne tespiti yapmak istediğimiz görseller:

#image1 = cv.imread("pug.jpg")
#image1 = cv.imread("guinea_pig.jpg")
image1 = cv.imread("zebra.jpg")

In [8]:
blob = cv.dnn.blobFromImage(image1,
                            1.0,
                            (224, 224),
                            (104, 117, 123),
                            False,
                            crop=False)

In [9]:
result = np.copy(image1)

In [10]:
net.setInput(blob)
out = net.forward()

In [11]:
out = out.flatten()
out[1:5]

array([4.3838301e-12, 1.3566291e-11, 5.8438165e-10, 7.4265614e-11],
      dtype=float32)

In [12]:
classId = np.argmax(out)
classId

340

In [13]:
confidence = out[classId]
confidence

0.99998736

In [14]:
t, _ = net.getPerfProfile()
label = 'cost time: %.2f ms' % (t * 1000.0/cv.getTickFrequency())
cv.putText(result,
           label,
           (0, 160),
           cv.FONT_HERSHEY_SIMPLEX,
           2,
           (255, 255, 0),
           10)

array([[[231, 233, 243],
        [232, 234, 244],
        [233, 235, 245],
        ...,
        [238, 238, 250],
        [237, 237, 249],
        [237, 237, 249]],

       [[231, 233, 243],
        [232, 234, 244],
        [233, 235, 245],
        ...,
        [238, 238, 250],
        [237, 237, 249],
        [237, 237, 249]],

       [[231, 233, 243],
        [232, 234, 244],
        [233, 235, 245],
        ...,
        [238, 238, 250],
        [237, 237, 249],
        [237, 237, 249]],

       ...,

       [[ 85, 113, 154],
        [ 56,  92, 132],
        [ 50, 102, 143],
        ...,
        [  0,  23,  39],
        [ 29,  43,  66],
        [ 23,  32,  59]],

       [[ 53,  75, 116],
        [ 24,  59,  99],
        [ 79, 135, 176],
        ...,
        [ 29,  42,  58],
        [ 83,  90, 117],
        [147, 152, 183]],

       [[ 52,  71, 109],
        [ 45,  75, 116],
        [ 59, 115, 156],
        ...,
        [ 48,  50,  61],
        [ 64,  75,  97],
        [126, 138, 166]]

In [15]:
print(label)

cost time: 74.04 ms


In [16]:
label = '%s : %.6f' % (classes[classId] if classes else 'class #%d' % classId, confidence)
cv.putText(result,
           label,
           (0, 260),
           cv.FONT_HERSHEY_SIMPLEX,
           2,
           (0, 0, 255),
           10)

array([[[231, 233, 243],
        [232, 234, 244],
        [233, 235, 245],
        ...,
        [238, 238, 250],
        [237, 237, 249],
        [237, 237, 249]],

       [[231, 233, 243],
        [232, 234, 244],
        [233, 235, 245],
        ...,
        [238, 238, 250],
        [237, 237, 249],
        [237, 237, 249]],

       [[231, 233, 243],
        [232, 234, 244],
        [233, 235, 245],
        ...,
        [238, 238, 250],
        [237, 237, 249],
        [237, 237, 249]],

       ...,

       [[ 85, 113, 154],
        [ 56,  92, 132],
        [ 50, 102, 143],
        ...,
        [  0,  23,  39],
        [ 29,  43,  66],
        [ 23,  32,  59]],

       [[ 53,  75, 116],
        [ 24,  59,  99],
        [ 79, 135, 176],
        ...,
        [ 29,  42,  58],
        [ 83,  90, 117],
        [147, 152, 183]],

       [[ 52,  71, 109],
        [ 45,  75, 116],
        [ 59, 115, 156],
        ...,
        [ 48,  50,  61],
        [ 64,  75,  97],
        [126, 138, 166]]

In [17]:
print(label)

zebra : 0.999987


In [18]:
show_img = np.hstack((image1, result))
cv.namedWindow('demo', cv.WINDOW_NORMAL)
cv.imshow("demo", show_img)
cv.waitKey(0)
cv.destroyAllWindows()
cv.imwrite("results2.jpg",show_img)

True

![](results1.jpg)

![](results2.jpg)

![](results3.jpg)