In [1]:
import numpy as np

In [2]:
a = [1,2,3,4,5]
b = [9,8,7,6,5]
a
b

[9, 8, 7, 6, 5]

In [3]:
a

[1, 2, 3, 4, 5]

In [4]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
b = np.array([10,20,30,40,50,60,70,80,90,100])
a*b


array([  10,   40,   90,  160,  250,  360,  490,  640,  810, 1000])

In [5]:
c = np.array([1,2.4,3, 4.3131])
c

array([1.    , 2.4   , 3.    , 4.3131])

In [6]:
np.zeros((5,5), dtype='int')

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [7]:
np.ones((9,9), dtype="int")

array([[1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [8]:
np.full((6,6), 31)

array([[31, 31, 31, 31, 31, 31],
       [31, 31, 31, 31, 31, 31],
       [31, 31, 31, 31, 31, 31],
       [31, 31, 31, 31, 31, 31],
       [31, 31, 31, 31, 31, 31],
       [31, 31, 31, 31, 31, 31]])

In [9]:
np.full((3,3,3,3,3),31)

array([[[[[31, 31, 31],
          [31, 31, 31],
          [31, 31, 31]],

         [[31, 31, 31],
          [31, 31, 31],
          [31, 31, 31]],

         [[31, 31, 31],
          [31, 31, 31],
          [31, 31, 31]]],


        [[[31, 31, 31],
          [31, 31, 31],
          [31, 31, 31]],

         [[31, 31, 31],
          [31, 31, 31],
          [31, 31, 31]],

         [[31, 31, 31],
          [31, 31, 31],
          [31, 31, 31]]],


        [[[31, 31, 31],
          [31, 31, 31],
          [31, 31, 31]],

         [[31, 31, 31],
          [31, 31, 31],
          [31, 31, 31]],

         [[31, 31, 31],
          [31, 31, 31],
          [31, 31, 31]]]],



       [[[[31, 31, 31],
          [31, 31, 31],
          [31, 31, 31]],

         [[31, 31, 31],
          [31, 31, 31],
          [31, 31, 31]],

         [[31, 31, 31],
          [31, 31, 31],
          [31, 31, 31]]],


        [[[31, 31, 31],
          [31, 31, 31],
          [31, 31, 31]],

         [[31, 31, 31],
    

In [10]:
np.arange(0,1000,31)

array([  0,  31,  62,  93, 124, 155, 186, 217, 248, 279, 310, 341, 372,
       403, 434, 465, 496, 527, 558, 589, 620, 651, 682, 713, 744, 775,
       806, 837, 868, 899, 930, 961, 992])

In [11]:
np.linspace(0,100, 1000, dtype='int')

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   1,   1,   1,
         1,   1,   1,   1,   1,   1,   1,   2,   2,   2,   2,   2,   2,
         2,   2,   2,   2,   3,   3,   3,   3,   3,   3,   3,   3,   3,
         3,   4,   4,   4,   4,   4,   4,   4,   4,   4,   4,   5,   5,
         5,   5,   5,   5,   5,   5,   5,   5,   6,   6,   6,   6,   6,
         6,   6,   6,   6,   6,   7,   7,   7,   7,   7,   7,   7,   7,
         7,   7,   8,   8,   8,   8,   8,   8,   8,   8,   8,   8,   9,
         9,   9,   9,   9,   9,   9,   9,   9,   9,  10,  10,  10,  10,
        10,  10,  10,  10,  10,  10,  11,  11,  11,  11,  11,  11,  11,
        11,  11,  11,  12,  12,  12,  12,  12,  12,  12,  12,  12,  12,
        13,  13,  13,  13,  13,  13,  13,  13,  13,  13,  14,  14,  14,
        14,  14,  14,  14,  14,  14,  14,  15,  15,  15,  15,  15,  15,
        15,  15,  15,  15,  16,  16,  16,  16,  16,  16,  16,  16,  16,
        16,  17,  17,  17,  17,  17,  17,  17,  17,  17,  17,  1

In [12]:
np.random.normal(10, 1000, (3,4))

array([[  749.91412884,  1175.98619336,  -625.19618256, -1470.50043852],
       [  441.15700883,  1107.18020685,  -461.70434392, -1811.49769221],
       [ -177.53864333,   814.32177   ,  -593.64820519,  2851.27383071]])

In [13]:
np.random.randint(0,31, (5,5))

array([[14, 16, 11,  9,  0],
       [11,  6,  0,  6, 27],
       [14,  4, 30, 30,  4],
       [12, 13, 20, 26, 13],
       [ 4, 18, 23,  4, 14]], dtype=int32)

* **ndim:** _boyut sayısı_ 
* **shape:**_boyut bilgisi_
* **size:** _toplam eleman sayısı_
* **dtype:**_array veri tipi_

In [14]:
a = np.random.randint(0,10, (10,5,2,3))
print(a)
print("boyut sayisi: " + str(a.ndim))
print("boyut bilgisi: " + str(a.shape))
print("toplam eleman sayisi: " + str(a.size))
print("array veri tipi: " + str(a.dtype))

[[[[1 6 3]
   [1 2 5]]

  [[0 6 2]
   [9 5 5]]

  [[3 3 3]
   [6 6 7]]

  [[0 1 7]
   [9 0 1]]

  [[1 0 4]
   [9 0 4]]]


 [[[8 7 5]
   [4 1 0]]

  [[7 5 9]
   [9 1 7]]

  [[8 0 8]
   [9 8 5]]

  [[7 0 1]
   [2 2 8]]

  [[8 0 8]
   [3 0 3]]]


 [[[8 4 2]
   [4 8 9]]

  [[9 6 5]
   [6 6 4]]

  [[7 5 3]
   [1 9 6]]

  [[7 5 8]
   [5 9 8]]

  [[0 9 4]
   [0 4 7]]]


 [[[0 8 3]
   [8 2 6]]

  [[9 3 8]
   [8 4 6]]

  [[0 1 1]
   [1 7 6]]

  [[1 1 7]
   [9 4 5]]

  [[2 4 2]
   [9 2 8]]]


 [[[1 8 0]
   [6 3 2]]

  [[1 5 6]
   [3 4 1]]

  [[5 4 7]
   [1 9 6]]

  [[4 2 1]
   [3 8 7]]

  [[7 0 0]
   [2 9 0]]]


 [[[6 0 0]
   [3 1 5]]

  [[0 3 3]
   [7 5 4]]

  [[0 5 1]
   [3 5 6]]

  [[5 2 9]
   [8 4 7]]

  [[4 4 7]
   [4 8 6]]]


 [[[8 5 7]
   [9 2 6]]

  [[6 2 4]
   [2 6 9]]

  [[0 4 3]
   [4 4 2]]

  [[4 2 8]
   [7 4 9]]

  [[3 3 1]
   [2 4 7]]]


 [[[0 5 2]
   [2 5 3]]

  [[3 5 7]
   [7 1 1]]

  [[3 3 4]
   [6 5 3]]

  [[9 7 8]
   [6 5 0]]

  [[5 2 5]
   [0 1 2]]]


 [[[3 0 2]
   [9 3 9]]



In [15]:
a= np.arange(1,65)
print(a)
print("\n\n\n")
print(a.reshape(8,8))
print("\n\n\n")
print(a.reshape(4,4,4))
print("\n\n\n")

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64]




[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32]
 [33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48]
 [49 50 51 52 53 54 55 56]
 [57 58 59 60 61 62 63 64]]




[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]
  [25 26 27 28]
  [29 30 31 32]]

 [[33 34 35 36]
  [37 38 39 40]
  [41 42 43 44]
  [45 46 47 48]]

 [[49 50 51 52]
  [53 54 55 56]
  [57 58 59 60]
  [61 62 63 64]]]






In [16]:
x = np.array([1,2,3,4])
y = np.array([5,6,1,22,31])
np.concatenate([x,y])

array([ 1,  2,  3,  4,  5,  6,  1, 22, 31])

In [17]:
a = np.array([[1,2,3],
              [4,5,6]])
np.concatenate([a,a])



array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [18]:
np.concatenate([a,a], axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [19]:
x = np.array([1,2,3,99,99,3,2,1])

a,b,c,d = np.split(x,[3,5,7])
print(a)
print(b)
print(c)
print(d)



[1 2 3]
[99 99]
[3 2]
[1]


In [20]:
m = np.arange(16).reshape(4,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [21]:
ust, alt = np.vsplit(m, [2])
print(ust)
print('\n')
print(alt)

[[0 1 2 3]
 [4 5 6 7]]


[[ 8  9 10 11]
 [12 13 14 15]]


In [22]:
sol, sag = np.hsplit(m, [2])
print(sol)
print('\n')
print(sag)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]


[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [23]:
v = np.array([1,2,3,41241,314134,0,-2412,31])
v

array([     1,      2,      3,  41241, 314134,      0,  -2412,     31])

In [24]:
np.sort(v)


array([ -2412,      0,      1,      2,      3,     31,  41241, 314134])

In [25]:
v

array([     1,      2,      3,  41241, 314134,      0,  -2412,     31])

In [26]:
v.sort()
v

array([ -2412,      0,      1,      2,      3,     31,  41241, 314134])

In [27]:
m = np.random.normal(20,50, (4,4))
m

array([[ 15.9864383 ,  91.83814128,  49.46612048,  41.96709758],
       [ 82.75758366,  65.41613632,  54.26137985,  18.95075447],
       [-25.38261216,  81.60635558,  -9.60977629,  72.4311514 ],
       [ 61.77154086,  22.24446338,  -3.0553287 ,  40.65723855]])

In [28]:
np.sort(m,axis=1)

array([[ 15.9864383 ,  41.96709758,  49.46612048,  91.83814128],
       [ 18.95075447,  54.26137985,  65.41613632,  82.75758366],
       [-25.38261216,  -9.60977629,  72.4311514 ,  81.60635558],
       [ -3.0553287 ,  22.24446338,  40.65723855,  61.77154086]])

In [29]:
np.sort(m,axis=0)

array([[-25.38261216,  22.24446338,  -9.60977629,  18.95075447],
       [ 15.9864383 ,  65.41613632,  -3.0553287 ,  40.65723855],
       [ 61.77154086,  81.60635558,  49.46612048,  41.96709758],
       [ 82.75758366,  91.83814128,  54.26137985,  72.4311514 ]])

In [30]:
a = np.random.randint(10, size=10)
a

array([5, 3, 6, 8, 8, 6, 7, 8, 5, 3], dtype=int32)

In [31]:
print(str(a[0])+" "+ str(a[1]) +" "+ str(a[-1]))

5 3 3


In [32]:
a = np.random.randint(10, size=(10,10))
a

array([[4, 9, 9, 8, 8, 1, 4, 2, 9, 9],
       [5, 9, 2, 3, 6, 8, 0, 3, 0, 8],
       [2, 2, 1, 3, 3, 7, 2, 9, 0, 3],
       [4, 1, 0, 8, 9, 0, 6, 2, 7, 8],
       [9, 0, 7, 1, 1, 5, 8, 3, 1, 4],
       [1, 6, 7, 3, 6, 5, 0, 6, 8, 3],
       [1, 0, 5, 9, 8, 5, 6, 1, 7, 9],
       [8, 6, 7, 7, 1, 5, 7, 4, 8, 9],
       [1, 2, 6, 8, 4, 9, 7, 6, 6, 1],
       [0, 4, 6, 7, 5, 5, 6, 5, 0, 0]], dtype=int32)

In [33]:
print(str(a[0,0])+" "+ str(a[1,8]) +" "+ str(a[-1,-1]))

4 0 0


In [34]:
a = np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [35]:
a[0:5]

array([20, 21, 22, 23, 24])

In [36]:
a[:3]

array([20, 21, 22])

In [37]:
a[4:]

array([24, 25, 26, 27, 28, 29])

In [38]:
a[1::2]

array([21, 23, 25, 27, 29])

In [39]:
b = np.random.randint(10, size=(5,5))
b

array([[2, 2, 0, 7, 3],
       [2, 2, 7, 0, 4],
       [8, 1, 8, 8, 8],
       [9, 3, 4, 8, 3],
       [8, 8, 4, 7, 7]], dtype=int32)

In [40]:
b[:,0]

array([2, 2, 8, 9, 8], dtype=int32)

In [41]:
b[:,3]

array([7, 0, 8, 8, 7], dtype=int32)

In [42]:
b[2,:]

array([8, 1, 8, 8, 8], dtype=int32)

In [43]:
b[2]

array([8, 1, 8, 8, 8], dtype=int32)

In [44]:
b[0:2, 0:3]

array([[2, 2, 0],
       [2, 2, 7]], dtype=int32)

In [45]:
b[:,:2]

array([[2, 2],
       [2, 2],
       [8, 1],
       [9, 3],
       [8, 8]], dtype=int32)

In [46]:
b[1:3,0:2]

array([[2, 2],
       [8, 1]], dtype=int32)

In [47]:
a = np.random.randint(10, size = (5,5))
a

array([[4, 5, 3, 1, 0],
       [3, 0, 3, 7, 0],
       [1, 4, 0, 4, 0],
       [8, 9, 5, 9, 3],
       [6, 0, 9, 7, 4]], dtype=int32)

In [48]:
alt_a = a[0:3,0:2]
alt_a

array([[4, 5],
       [3, 0],
       [1, 4]], dtype=int32)

In [49]:
alt_a[0,0] = 313131
alt_a[1,1] = 696969

In [50]:
alt_a

array([[313131,      5],
       [     3, 696969],
       [     1,      4]], dtype=int32)

In [51]:
a

array([[313131,      5,      3,      1,      0],
       [     3, 696969,      3,      7,      0],
       [     1,      4,      0,      4,      0],
       [     8,      9,      5,      9,      3],
       [     6,      0,      9,      7,      4]], dtype=int32)

In [52]:
b = np.random.randint(10, size = (5,5))
b

array([[7, 4, 4, 8, 7],
       [7, 5, 9, 2, 4],
       [5, 3, 1, 9, 7],
       [5, 1, 9, 2, 7],
       [8, 4, 9, 5, 2]], dtype=int32)

In [53]:
alt_b = b[0:3,0:2].copy()
alt_b

array([[7, 4],
       [7, 5],
       [5, 3]], dtype=int32)

In [54]:
alt_b[0,0] = 313131
alt_b[1,1] = 696969

In [55]:
alt_b

array([[313131,      4],
       [     7, 696969],
       [     5,      3]], dtype=int32)

In [56]:
b

array([[7, 4, 4, 8, 7],
       [7, 5, 9, 2, 4],
       [5, 3, 1, 9, 7],
       [5, 1, 9, 2, 7],
       [8, 4, 9, 5, 2]], dtype=int32)

In [57]:
v = np.arange(0, 30, 3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [58]:
v[2].item()

6

In [59]:
[v[1].item(),v[3].item(),v[5].item()]

[3, 9, 15]

In [60]:
al_getir = [1,3,5]
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [61]:
v[al_getir]

array([ 3,  9, 15])

In [62]:
m = np.arange(9).reshape((3,3))
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [63]:
satir = np.array([0,1])
sutun = np.array([1,2])

In [64]:
m[satir, sutun]

array([1, 5])

In [65]:
#basit index ile fancy index

In [66]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [67]:
m[2, [1,2]]

array([7, 8])

In [68]:
#slice ile fancy

In [69]:
m[0:, [1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [70]:
m[1:, [1,2]]

array([[4, 5],
       [7, 8]])

In [71]:
#kosullu eleman islemleri

In [72]:
v = np.array([1,2,3,4,5,6,7,8,9,10])
v

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [73]:
v > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [74]:
v[v>5]

array([ 6,  7,  8,  9, 10])

In [75]:
v*2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [76]:
v

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [77]:
#ufunc

In [78]:
np.subtract(v,1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
v

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [80]:
print(str(v))
print(str(np.subtract(v, 5)))
print(str(np.add(v, 5)))
print(str(np.multiply(v, 5)))
print(str(np.divide(v, 5)))
print(str(np.power(v,5)))
print(str(np.mod(v,5)))
print(str(np.absolute(np.array([-1,-2,-312,0,312]))))
# angles = np.array([0, 30, 45, 60, 90, 120, 135, 150, 180])
# radian_angles = np.radians(angles)
# print(str(radian_angles))
# print(str(np.sin(np.radians(radian_angles))))
print(str(np.log(v)))
print(str(np.log2(v)))
print(str(np.log10(v)))


[ 1  2  3  4  5  6  7  8  9 10]
[-4 -3 -2 -1  0  1  2  3  4  5]
[ 6  7  8  9 10 11 12 13 14 15]
[ 5 10 15 20 25 30 35 40 45 50]
[0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8 2. ]
[     1     32    243   1024   3125   7776  16807  32768  59049 100000]
[1 2 3 4 0 1 2 3 4 0]
[  1   2 312   0 312]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458 2.30258509]
[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925   3.32192809]
[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251 1.        ]


In [81]:
?np

Type:        module
String form: <module 'numpy' from 'c:\\Users\\Giray\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\numpy\\__init__.py'>
File:        c:\users\giray\appdata\local\programs\python\python312\lib\site-packages\numpy\__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets

In [82]:
#cheatsheet
# numpy mathematics cheat sheet diye aratılabilir

5*x0 +   x1 = 12
 
x0   + 3*x1 = 10

In [83]:
a = np.array([[5,1],
              [1,3]])
b = np.array([12,10])

In [84]:
a

array([[5, 1],
       [1, 3]])

In [85]:
b

array([12, 10])

In [86]:
x = np.linalg.solve(a, b)
x

array([1.85714286, 2.71428571])

In [87]:
np.arange(0,10, 2)

array([0, 2, 4, 6, 8])