In [13]:
import cv2 as cv
import numpy as np
import os

In [14]:
#klasör konumu
current_dir = os.getcwd()

In [15]:
#resmi okuma
src = cv.imread("turkish_liras.png")
cv.namedWindow("input", cv.WINDOW_AUTOSIZE)
cv.imshow("input", src)
cv.waitKey(10)

-1

In [16]:
#gri yapma
gray = cv.cvtColor(src, cv.COLOR_BGR2GRAY)
cv.imshow("gray", gray)
cv.waitKey(10)

#gri görüntüyü kaydet
gray_image_path = os.path.join(current_dir, "gray_image.png")
cv.imwrite(gray_image_path, gray)

True

In [17]:
#gürültü azaltma
gray = cv.GaussianBlur(gray, (9,9), 2, 2)
cv.imshow("Blured Gray", gray)
cv.waitKey(10)

#blured gray görüntüyü kaydet
blured_gray_image_path = os.path.join(current_dir, "blured_gray_image.png")
cv.imwrite(blured_gray_image_path, gray)

True

In [18]:
#Circle Detection
circles = cv.HoughCircles(gray,    #blured gray image
                          cv.HOUGH_GRADIENT, 
                          dp        = 1,        # Çözünürlüğü düşürme katsayısı
                          minDist   = 50,       # Daireler arası minimum mesafe
                          param1    = 100,      # Canny kenar tespit üst sınırı
                          param2    = 40,       # Daire tespiti için eşik değeri
                          minRadius = 20,       # En küçük daire yarıçapı
                          maxRadius = 200)      # En büyük daire yarıçapı
if circles is not None:
    circles = np.uint16((np.around(circles))) # Daire koordinatlarını tam sayılara yuvarla
    for c in circles[0, :]:
        print(c)
        cx, cy, r = c
        cx, cy, r = int(cx), int(cy), int(r) # Tam sayıya dönüştür
        cv.circle(src, (cx,cy), 2, (0,255,0), 2, 8, 0) #Merkezleri çiz
        cv.circle(src, (cx,cy), r, (0,0,255), 2, 8, 0) #Daireleri çiz

[378 274 108]
[300  94  85]
[200 390 104]
[136 114  79]
[ 88 256  74]


In [19]:
#Hoofman Circle Detection Image
cv.imshow("Hough Circle Demo", src)
cv.waitKey(10)

#Hoffman Circle Detection image kaydet
hoffman_circle_detection_image_path = os.path.join(current_dir, "hoffman_circle_detection_image.png")
cv.imwrite(hoffman_circle_detection_image_path, src)

True

In [20]:
cv.waitKey(0)
cv.destroyAllWindows()

In [21]:
# Ekstra satırlar olmadan kod;

#Resmi okuma
src = cv.imread("turkish_liras.png")
#gri yapma
gray = cv.cvtColor(src, cv.COLOR_BGR2GRAY)
#gürültü azaltma
gray = cv.GaussianBlur(gray, (9,9), 2, 2)

#Circle Detection
circles = cv.HoughCircles(gray,    #blured gray image
                          cv.HOUGH_GRADIENT, 
                          dp        = 1,        # Çözünürlüğü düşürme katsayısı
                          minDist   = 50,       # Daireler arası minimum mesafe
                          param1    = 100,      # Canny kenar tespit üst sınırı
                          param2    = 40,       # Daire tespiti için eşik değeri
                          minRadius = 20,       # En küçük daire yarıçapı
                          maxRadius = 200)      # En büyük daire yarıçapı
if circles is not None:
    circles = np.uint16((np.around(circles))) # Daire koordinatlarını tam sayılara yuvarla
    for c in circles[0, :]:
        print(c)
        cx, cy, r = c
        cx, cy, r = int(cx), int(cy), int(r) # Tam sayıya dönüştür
        cv.circle(src, (cx,cy), 2, (0,255,0), 2, 8, 0) #Merkezleri çiz
        cv.circle(src, (cx,cy), r, (0,0,255), 2, 8, 0) #Daireleri çiz

#Hoofman Circle Detection Image gösterme
cv.imshow("Hough Circle Demo", src)
cv.waitKey(0)
cv.destroyAllWindows()

[378 274 108]
[300  94  85]
[200 390 104]
[136 114  79]
[ 88 256  74]
