In [764]:
import pandas as pd
import numpy as np

In [765]:
p = pd.Series([1,2,3,4,5,6,67,8341,31])
p

0       1
1       2
2       3
3       4
4       5
5       6
6      67
7    8341
8      31
dtype: int64

In [766]:
type(p)

pandas.core.series.Series

In [767]:
p.axes

[RangeIndex(start=0, stop=9, step=1)]

In [768]:
p.dtype

dtype('int64')

In [769]:
p.ndim

1

In [770]:
p.values

array([   1,    2,    3,    4,    5,    6,   67, 8341,   31])

In [771]:
print(p)
print("boyut sayisi: " + str(p.ndim))
print("boyut bilgisi: " + str(p.shape))
print("toplam eleman sayisi: " + str(p.size))
print("array veri tipi: " + str(p.dtype))

0       1
1       2
2       3
3       4
4       5
5       6
6      67
7    8341
8      31
dtype: int64
boyut sayisi: 1
boyut bilgisi: (9,)
toplam eleman sayisi: 9
array veri tipi: int64


In [772]:
p.head(2) #ilk 2 eleman

0    1
1    2
dtype: int64

In [773]:
p.tail(2) #son 2 eleman

7    8341
8      31
dtype: int64

In [774]:
#index isimlendirme

In [775]:
a = pd.Series([99,22,33,44,556,66,777,889,9990,000], index=[1,3,5,7,9,11,13,15,17,19])
a

1       99
3       22
5       33
7       44
9      556
11      66
13     777
15     889
17    9990
19       0
dtype: int64

In [776]:
a.axes

[Index([1, 3, 5, 7, 9, 11, 13, 15, 17, 19], dtype='int64')]

In [777]:
a = pd.Series([99,22,33,44,556,66,777,889,9990,000], index=[1,"istanbul",5,7,9,11,"Ankara",15,17,19])
a

1             99
istanbul      22
5             33
7             44
9            556
11            66
Ankara       777
15           889
17          9990
19             0
dtype: int64

In [778]:
a["istanbul"]

np.int64(22)

In [779]:
a["istanbul":"Ankara"]

istanbul     22
5            33
7            44
9           556
11           66
Ankara      777
dtype: int64

## Sozluk ile liste olusturmak

In [780]:
sozluk = pd.Series({"aslan":31,"kaplan":26,"sirtlan":41})

In [781]:
sozluk

aslan      31
kaplan     26
sirtlan    41
dtype: int64

In [782]:
sozluk2 = {"aslan":31,"kaplan":26,"sirtlan":41}

In [783]:
seri = pd.Series(sozluk2)

In [784]:
seri

aslan      31
kaplan     26
sirtlan    41
dtype: int64

## iki seriyi birleştirerek seri oluşturma

In [785]:
pd.concat([seri,seri])

aslan      31
kaplan     26
sirtlan    41
aslan      31
kaplan     26
sirtlan    41
dtype: int64

## Eleman islemleri


In [786]:
a = np.array([1123,2133421,331531,4315315,53151355,6315135])
a

array([    1123,  2133421,   331531,  4315315, 53151355,  6315135])

In [787]:
seri = pd.Series(a)
seri

0        1123
1     2133421
2      331531
3     4315315
4    53151355
5     6315135
dtype: int64

In [788]:
seri[0]

np.int64(1123)

In [789]:
seri[0:3]

0       1123
1    2133421
2     331531
dtype: int64

In [790]:
seri = pd.Series([132,231,331,431,531],
                 index = ["zoro","tenyson","vilgax","venom","rimuru"])

In [791]:
seri

zoro       132
tenyson    231
vilgax     331
venom      431
rimuru     531
dtype: int64

In [792]:
seri.index

Index(['zoro', 'tenyson', 'vilgax', 'venom', 'rimuru'], dtype='object')

In [793]:
seri.keys

<bound method Series.keys of zoro       132
tenyson    231
vilgax     331
venom      431
rimuru     531
dtype: int64>

In [794]:
list(seri.items())

[('zoro', 132),
 ('tenyson', 231),
 ('vilgax', 331),
 ('venom', 431),
 ('rimuru', 531)]

In [795]:
seri.values

array([132, 231, 331, 431, 531])

# eleman sorgulama

In [796]:
"rimuru" in seri

True

In [797]:
"spiderman" in seri

False

In [798]:
seri["rimuru"]

np.int64(531)

# fancy eleman

In [799]:
seri[["venom","vilgax"]]

venom     431
vilgax    331
dtype: int64

In [800]:
seri["vilgax"] = 313131

In [801]:
seri["vilgax"]

np.int64(313131)

In [802]:
deger = seri["vilgax"]

In [803]:
print(deger)

313131


## PANDAS DataFrame Olusturma

In [804]:
l = [131,231,312412,4153135,543163456,61636]
l

[131, 231, 312412, 4153135, 543163456, 61636]

In [805]:
pd.DataFrame(l, columns= ["degisken_ismi"])

degisken_ismi
0            131
1            231
2         312412
3        4153135
4      543163456
5          61636

In [806]:
m = np.arange(1,101).reshape((10,10))
m

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [807]:
pd.DataFrame(m, columns=["var1","var2","var3","var4","var5","var6","var7","var8","var9","var10"], )

var1  var2  var3  var4  var5  var6  var7  var8  var9  var10
0     1     2     3     4     5     6     7     8     9     10
1    11    12    13    14    15    16    17    18    19     20
2    21    22    23    24    25    26    27    28    29     30
3    31    32    33    34    35    36    37    38    39     40
4    41    42    43    44    45    46    47    48    49     50
5    51    52    53    54    55    56    57    58    59     60
6    61    62    63    64    65    66    67    68    69     70
7    71    72    73    74    75    76    77    78    79     80
8    81    82    83    84    85    86    87    88    89     90
9    91    92    93    94    95    96    97    98    99    100

# df (DataFrame) isimlendirme

In [808]:
df = pd.DataFrame(m, columns = ["var1","var2","var3","var4","var5","var6","var7","var8","var9","var10"])
df

var1  var2  var3  var4  var5  var6  var7  var8  var9  var10
0     1     2     3     4     5     6     7     8     9     10
1    11    12    13    14    15    16    17    18    19     20
2    21    22    23    24    25    26    27    28    29     30
3    31    32    33    34    35    36    37    38    39     40
4    41    42    43    44    45    46    47    48    49     50
5    51    52    53    54    55    56    57    58    59     60
6    61    62    63    64    65    66    67    68    69     70
7    71    72    73    74    75    76    77    78    79     80
8    81    82    83    84    85    86    87    88    89     90
9    91    92    93    94    95    96    97    98    99    100

In [809]:
df.columns = ("a","b","c","d","e","f","g","h","i","j")
df

a   b   c   d   e   f   g   h   i    j
0   1   2   3   4   5   6   7   8   9   10
1  11  12  13  14  15  16  17  18  19   20
2  21  22  23  24  25  26  27  28  29   30
3  31  32  33  34  35  36  37  38  39   40
4  41  42  43  44  45  46  47  48  49   50
5  51  52  53  54  55  56  57  58  59   60
6  61  62  63  64  65  66  67  68  69   70
7  71  72  73  74  75  76  77  78  79   80
8  81  82  83  84  85  86  87  88  89   90
9  91  92  93  94  95  96  97  98  99  100

In [810]:
print(df)
print("\n")
print("boyut sayisi: " + str(df.ndim))
print("\n")
print("boyut bilgisi: " + str(df.shape))
print("\n")
print("toplam eleman sayisi: " + str(df.size))
print("\n")
print("array veri tipi: " + str(df.dtypes))
print("\n")
print("array degerleri: " + str(df.values))
print("\n")
print("df.values'in veri tipi: "+ str(type(df.values)))

    a   b   c   d   e   f   g   h   i    j
0   1   2   3   4   5   6   7   8   9   10
1  11  12  13  14  15  16  17  18  19   20
2  21  22  23  24  25  26  27  28  29   30
3  31  32  33  34  35  36  37  38  39   40
4  41  42  43  44  45  46  47  48  49   50
5  51  52  53  54  55  56  57  58  59   60
6  61  62  63  64  65  66  67  68  69   70
7  71  72  73  74  75  76  77  78  79   80
8  81  82  83  84  85  86  87  88  89   90
9  91  92  93  94  95  96  97  98  99  100


boyut sayisi: 2


boyut bilgisi: (10, 10)


toplam eleman sayisi: 100


array veri tipi: a    int64
b    int64
c    int64
d    int64
e    int64
f    int64
g    int64
h    int64
i    int64
j    int64
dtype: object


array degerleri: [[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  

In [811]:
a = np.array([1,2,3,4,54,56,5312])
a

array([   1,    2,    3,    4,   54,   56, 5312])

In [812]:
pd.DataFrame(a, columns=["deg1"])

deg1
0     1
1     2
2     3
3     4
4    54
5    56
6  5312

In [813]:
s1 = np.random.randint(10, size = 5)
s2 = np.random.randint(10, size = 5)
s3 = np.random.randint(10, size = 5)

In [814]:
sozluk = {"var1":s1, "var2":s2, "var3":s3}
sozluk

{'var1': array([2, 2, 5, 3, 9], dtype=int32),
 'var2': array([2, 8, 4, 3, 4], dtype=int32),
 'var3': array([5, 8, 0, 3, 7], dtype=int32)}

In [815]:
df = pd.DataFrame(sozluk)
df

var1  var2  var3
0     2     2     5
1     2     8     8
2     5     4     0
3     3     3     3
4     9     4     7

In [816]:
df[0:1]

var1  var2  var3
0     2     2     5

In [817]:
df[0:4:2]

var1  var2  var3
0     2     2     5
2     5     4     0

In [818]:
df

var1  var2  var3
0     2     2     5
1     2     8     8
2     5     4     0
3     3     3     3
4     9     4     7

In [819]:
df.index = ["a","b","c","d","e"]
df

var1  var2  var3
a     2     2     5
b     2     8     8
c     5     4     0
d     3     3     3
e     9     4     7

# silme

In [820]:
df.drop("a", axis=0)

var1  var2  var3
b     2     8     8
c     5     4     0
d     3     3     3
e     9     4     7

In [821]:
df

var1  var2  var3
a     2     2     5
b     2     8     8
c     5     4     0
d     3     3     3
e     9     4     7

In [822]:
df.drop("a")

var1  var2  var3
b     2     8     8
c     5     4     0
d     3     3     3
e     9     4     7

In [823]:
df.drop("c", axis = 0)

var1  var2  var3
a     2     2     5
b     2     8     8
d     3     3     3
e     9     4     7

In [824]:
#kalıcı değiştirmek için df = .... veya bu fonksiyon;
df.drop("c", axis=0, inplace=True)

In [825]:
df

var1  var2  var3
a     2     2     5
b     2     8     8
d     3     3     3
e     9     4     7

### fancy ile silme

In [826]:
l = ["b", "e"]

In [827]:
df.drop(l, axis=0, inplace=True)

In [828]:
df

var1  var2  var3
a     2     2     5
d     3     3     3

In [829]:
"var1" in df

True

In [830]:
l = ["var1","var2","var3","var4"]

In [831]:
for i in l:
    print(i in df)

True
True
True
False


In [832]:
df["var1"]

a    2
d    3
Name: var1, dtype: int32

In [833]:
df["var4"] = df["var1"]/df["var2"]

In [834]:
df

var1  var2  var3  var4
a     2     2     5   1.0
d     3     3     3   1.0

# degisken silme

In [835]:
df.drop("var4", axis=1)

var1  var2  var3
a     2     2     5
d     3     3     3

In [836]:
df

var1  var2  var3  var4
a     2     2     5   1.0
d     3     3     3   1.0

In [837]:
df.drop("var4", axis=1, inplace=True)

In [838]:
df

var1  var2  var3
a     2     2     5
d     3     3     3

## GÖZLEM VE DEĞİŞKEN SEÇİMİ: loc & iloc

In [839]:
m = np.random.randint(1,30, size=(10,3))
df = pd.DataFrame(m, columns=["var1","var2","var3"])
df

var1  var2  var3
0     7     4    13
1     9     6     2
2    28    17    19
3     1     9     7
4    14     1    17
5    28     7    21
6    29    20    14
7     4    14    24
8    20    15    16
9    21    28    15

loc: tanımlandığı şekli ile seçim yapmak için kullanılır.

In [840]:
df.loc[0:3]

var1  var2  var3
0     7     4    13
1     9     6     2
2    28    17    19
3     1     9     7

In [841]:
df.loc[6:8]

var1  var2  var3
6    29    20    14
7     4    14    24
8    20    15    16

In [842]:
df.loc[5:3]

Empty DataFrame
Columns: [var1, var2, var3]
Index: []

iloc: alışık olduğumuz indeksleme mantığı ile seçim yapar.

In [843]:
df.iloc[0:3]

var1  var2  var3
0     7     4    13
1     9     6     2
2    28    17    19

In [844]:
df.loc[0:3]

var1  var2  var3
0     7     4    13
1     9     6     2
2    28    17    19
3     1     9     7

In [845]:
df.iloc[0,0]

np.int32(7)

In [846]:
df.iloc[:2,:3]

var1  var2  var3
0     7     4    13
1     9     6     2

In [847]:
df.loc[0:3,"var3"]

0    13
1     2
2    19
3     7
Name: var3, dtype: int32

In [848]:
df.iloc[0:3]["var3"]

0    13
1     2
2    19
Name: var3, dtype: int32

# koşullu eleman

In [849]:
m = np.random.randint(1,30, size=(10,3))
df = pd.DataFrame(m, columns=["var1","var2","var3"])
df

var1  var2  var3
0    15    25    16
1    18    18    17
2     6     4    20
3     1    23    21
4     4    23    26
5    18     9     2
6    14     5    18
7    16    21    22
8    23     4    11
9    29    29    21

In [850]:
df["var1"]

0    15
1    18
2     6
3     1
4     4
5    18
6    14
7    16
8    23
9    29
Name: var1, dtype: int32

In [851]:
df["var1"][0:2]

0    15
1    18
Name: var1, dtype: int32

In [852]:
df[0:2]

var1  var2  var3
0    15    25    16
1    18    18    17

In [853]:
df[0:2]["var1"]

0    15
1    18
Name: var1, dtype: int32

In [854]:
df[0:2][["var1","var2"]]

var1  var2
0    15    25
1    18    18

In [855]:
df

var1  var2  var3
0    15    25    16
1    18    18    17
2     6     4    20
3     1    23    21
4     4    23    26
5    18     9     2
6    14     5    18
7    16    21    22
8    23     4    11
9    29    29    21

In [856]:
df.var1

0    15
1    18
2     6
3     1
4     4
5    18
6    14
7    16
8    23
9    29
Name: var1, dtype: int32

In [857]:
df[df.var1 > 15]

var1  var2  var3
1    18    18    17
5    18     9     2
7    16    21    22
8    23     4    11
9    29    29    21

In [858]:
df[df.var1 > 15]["var1"]

1    18
5    18
7    16
8    23
9    29
Name: var1, dtype: int32

In [859]:
df[(df.var1 > 15) & (df.var3 < 8)]

var1  var2  var3
5    18     9     2

In [860]:
df.loc[(df.var1 > 15), ["var1","var2"]]

var1  var2
1    18    18
5    18     9
7    16    21
8    23     4
9    29    29

In [861]:
df[(df.var1 > 15)]["var1"]

1    18
5    18
7    16
8    23
9    29
Name: var1, dtype: int32

In [862]:
df[(df.var1 > 15)][["var1","var2"]]

var1  var2
1    18    18
5    18     9
7    16    21
8    23     4
9    29    29

# Birleştirme (Join) İşlemleri

In [863]:
m = np.random.randint(1,30, size=(5,3))
df1 = pd.DataFrame(m, columns=["var1","var2","var3"])
df1

var1  var2  var3
0    10     6    28
1    27    29     7
2     6    21    25
3    15    18    19
4    28    12    15

In [864]:
df2 = df1 + 31
df2

var1  var2  var3
0    41    37    59
1    58    60    38
2    37    52    56
3    46    49    50
4    59    43    46

In [865]:
pd.concat([df1,df2]) # indexlerde sıkıntı var çözelim.

var1  var2  var3
0    10     6    28
1    27    29     7
2     6    21    25
3    15    18    19
4    28    12    15
0    41    37    59
1    58    60    38
2    37    52    56
3    46    49    50
4    59    43    46

In [866]:
pd.concat([df1,df2], ignore_index=True)

var1  var2  var3
0    10     6    28
1    27    29     7
2     6    21    25
3    15    18    19
4    28    12    15
5    41    37    59
6    58    60    38
7    37    52    56
8    46    49    50
9    59    43    46

In [867]:
df1.columns

Index(['var1', 'var2', 'var3'], dtype='object')

In [868]:
df2.columns

Index(['var1', 'var2', 'var3'], dtype='object')

In [869]:
df2.columns = ["var1","var2","deg3"]

In [870]:
df2

var1  var2  deg3
0    41    37    59
1    58    60    38
2    37    52    56
3    46    49    50
4    59    43    46

In [871]:
df1

var1  var2  var3
0    10     6    28
1    27    29     7
2     6    21    25
3    15    18    19
4    28    12    15

In [872]:
pd.concat([df1, df2]) #nan'ları istemiyorsak;

var1  var2  var3  deg3
0    10     6  28.0   NaN
1    27    29   7.0   NaN
2     6    21  25.0   NaN
3    15    18  19.0   NaN
4    28    12  15.0   NaN
0    41    37   NaN  59.0
1    58    60   NaN  38.0
2    37    52   NaN  56.0
3    46    49   NaN  50.0
4    59    43   NaN  46.0

In [873]:
pd.concat([df1, df2], join="inner")

var1  var2
0    10     6
1    27    29
2     6    21
3    15    18
4    28    12
0    41    37
1    58    60
2    37    52
3    46    49
4    59    43

In [874]:
?pd.concat

Signature:
pd.concat(
    objs: 'Iterable[Series | DataFrame] | Mapping[HashableT, Series | DataFrame]',
    *,
    axis: 'Axis' = 0,
    join: 'str' = 'outer',
    ignore_index: 'bool' = False,
    keys: 'Iterable[Hashable] | None' = None,
    levels=None,
    names: 'list[HashableT] | None' = None,
    verify_integrity: 'bool' = False,
    sort: 'bool' = False,
    copy: 'bool | None' = None,
) -> 'DataFrame | Series'
Docstring:
Concatenate pandas objects along a particular axis.

Allows optional set logic along the other axes.

Can also add a layer of hierarchical indexing on the concatenation axis,
which may be useful if the labels are the same (or overlapping) on
the passed axis number.

Parameters
----------
objs : a sequence or mapping of Series or DataFrame objects
    If a mapping is passed, the sorted keys will be used as the `keys`
    argument, unless it is passed, in which case the values will be
    selected (see below). Any None objects will be dropped silently unless
  

In [875]:
pd.concat([df1, df2], axis=1, join="outer")

var1  var2  var3  var1  var2  deg3
0    10     6    28    41    37    59
1    27    29     7    58    60    38
2     6    21    25    37    52    56
3    15    18    19    46    49    50
4    28    12    15    59    43    46

In [876]:
df_combined = pd.concat([df1, df2], axis=0, ignore_index=False)
df_combined

var1  var2  var3  deg3
0    10     6  28.0   NaN
1    27    29   7.0   NaN
2     6    21  25.0   NaN
3    15    18  19.0   NaN
4    28    12  15.0   NaN
0    41    37   NaN  59.0
1    58    60   NaN  38.0
2    37    52   NaN  56.0
3    46    49   NaN  50.0
4    59    43   NaN  46.0

In [877]:
df_combined = df_combined.reindex(columns=["var1", "var2", "var3"])
df_combined

var1  var2  var3
0    10     6  28.0
1    27    29   7.0
2     6    21  25.0
3    15    18  19.0
4    28    12  15.0
0    41    37   NaN
1    58    60   NaN
2    37    52   NaN
3    46    49   NaN
4    59    43   NaN

# ileri birleştirme

In [878]:
df1 = pd.DataFrame({'Calisanlar' : ['Giray','Ayse', 'Veli', 'Mehmet'],
                    'Grup'       : ['Muhendislik', 'Muhasebe', 'IK', 'Muhendislik']
                    })
df1

Calisanlar         Grup
0      Giray  Muhendislik
1       Ayse     Muhasebe
2       Veli           IK
3     Mehmet  Muhendislik

In [879]:
df2 = pd.DataFrame({'Calisanlar' : ['Giray','Ayse', 'Veli', 'Mehmet'],
                    'ilk_giris'       : [2010, 2009, 2014, 2019]
                    })
df2

Calisanlar  ilk_giris
0      Giray       2010
1       Ayse       2009
2       Veli       2014
3     Mehmet       2019

In [880]:
pd.merge(df1,df2)

Calisanlar         Grup  ilk_giris
0      Giray  Muhendislik       2010
1       Ayse     Muhasebe       2009
2       Veli           IK       2014
3     Mehmet  Muhendislik       2019

In [881]:
pd.merge(df1,df2, on = "Calisanlar")

Calisanlar         Grup  ilk_giris
0      Giray  Muhendislik       2010
1       Ayse     Muhasebe       2009
2       Veli           IK       2014
3     Mehmet  Muhendislik       2019

## many to one

In [882]:
df3 = pd.merge(df1,df2)
df3

Calisanlar         Grup  ilk_giris
0      Giray  Muhendislik       2010
1       Ayse     Muhasebe       2009
2       Veli           IK       2014
3     Mehmet  Muhendislik       2019

In [883]:
df4 = pd.DataFrame({'Grup'  : ['Muhasebe','Muhendislik','IK'],
                    'Mudur' : ['Caner','Mustafa','Berkcan']
                    })
df4

Grup    Mudur
0     Muhasebe    Caner
1  Muhendislik  Mustafa
2           IK  Berkcan

In [884]:
pd.merge(df3,df4)

Calisanlar         Grup  ilk_giris    Mudur
0      Giray  Muhendislik       2010  Mustafa
1       Ayse     Muhasebe       2009    Caner
2       Veli           IK       2014  Berkcan
3     Mehmet  Muhendislik       2019  Mustafa

## Many to Many

In [885]:
df5 = pd.DataFrame({'Grup'       : ['Muhasebe','Muhasebe','Muhendislik','Muhendislik','IK','IK'],
                    'Yetenekler' : ['matematik','excel','kodlama','linux','excel','yonetim']
                    })
df5

Grup Yetenekler
0     Muhasebe  matematik
1     Muhasebe      excel
2  Muhendislik    kodlama
3  Muhendislik      linux
4           IK      excel
5           IK    yonetim

In [886]:
df1

Calisanlar         Grup
0      Giray  Muhendislik
1       Ayse     Muhasebe
2       Veli           IK
3     Mehmet  Muhendislik

In [887]:
pd.merge(df1,df5)

Calisanlar         Grup Yetenekler
0      Giray  Muhendislik    kodlama
1      Giray  Muhendislik      linux
2       Ayse     Muhasebe  matematik
3       Ayse     Muhasebe      excel
4       Veli           IK      excel
5       Veli           IK    yonetim
6     Mehmet  Muhendislik    kodlama
7     Mehmet  Muhendislik      linux

# TOPLULAŞTIRMA VE GRUPLAMA ( AGGREGATION & GROUPING )

basic aggregation functions:
* count()
* first()
* last()
* mean()
* median()
* min()
* max()
* std()
* var()
* sum()

In [888]:
import seaborn as sns

In [889]:
df = sns.load_dataset("planets")
df

method  number  orbital_period   mass  distance  year
0     Radial Velocity       1      269.300000   7.10     77.40  2006
1     Radial Velocity       1      874.774000   2.21     56.95  2008
2     Radial Velocity       1      763.000000   2.60     19.84  2011
3     Radial Velocity       1      326.030000  19.40    110.62  2007
4     Radial Velocity       1      516.220000  10.50    119.47  2009
...               ...     ...             ...    ...       ...   ...
1030          Transit       1        3.941507    NaN    172.00  2006
1031          Transit       1        2.615864    NaN    148.00  2007
1032          Transit       1        3.191524    NaN    174.00  2007
1033          Transit       1        4.125083    NaN    293.00  2008
1034          Transit       1        4.187757    NaN    260.00  2008

[1035 rows x 6 columns]

In [890]:
?sns.load_dataset

Signature: sns.load_dataset(name, cache=True, data_home=None, **kws)
Docstring:
Load an example dataset from the online repository (requires internet).

This function provides quick access to a small number of example datasets
that are useful for documenting seaborn or generating reproducible examples
for bug reports. It is not necessary for normal usage.

Note that some of the datasets have a small amount of preprocessing applied
to define a proper ordering for categorical variables.

Use :func:`get_dataset_names` to see a list of available datasets.

Parameters
----------
name : str
    Name of the dataset (``{name}.csv`` on
    https://github.com/mwaskom/seaborn-data).
cache : boolean, optional
    If True, try to load from the local cache first, and save to the cache
    if a download is required.
data_home : string, optional
    The directory in which to cache data; see :func:`get_data_home`.
kws : keys and values, optional
    Additional keyword arguments are passed to passed thr

In [891]:
df.head()

method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [892]:
df.shape

(1035, 6)

In [893]:
df.mean(numeric_only=True)

number               1.785507
orbital_period    2002.917596
mass                 2.638161
distance           264.069282
year              2009.070531
dtype: float64

In [894]:
df["mass"].mean()

np.float64(2.6381605847953216)

In [895]:
df["mass"].count()

np.int64(513)

In [896]:
df["mass"].min()

np.float64(0.0036)

In [897]:
df["mass"].max()

np.float64(25.0)

In [898]:
df["mass"].sum()

np.float64(1353.37638)

In [899]:
df["mass"].std()

np.float64(3.8186166509616046)

In [900]:
df["mass"].var()

np.float64(14.58183312700122)

In [901]:
df.describe()

number  orbital_period        mass     distance         year
count  1035.000000      992.000000  513.000000   808.000000  1035.000000
mean      1.785507     2002.917596    2.638161   264.069282  2009.070531
std       1.240976    26014.728304    3.818617   733.116493     3.972567
min       1.000000        0.090706    0.003600     1.350000  1989.000000
25%       1.000000        5.442540    0.229000    32.560000  2007.000000
50%       1.000000       39.979500    1.260000    55.250000  2010.000000
75%       2.000000      526.005000    3.040000   178.500000  2012.000000
max       7.000000   730000.000000   25.000000  8500.000000  2014.000000

In [902]:
df.describe().T

count         mean           std          min         25%  \
number          1035.0     1.785507      1.240976     1.000000     1.00000   
orbital_period   992.0  2002.917596  26014.728304     0.090706     5.44254   
mass             513.0     2.638161      3.818617     0.003600     0.22900   
distance         808.0   264.069282    733.116493     1.350000    32.56000   
year            1035.0  2009.070531      3.972567  1989.000000  2007.00000   

                      50%       75%       max  
number             1.0000     2.000       7.0  
orbital_period    39.9795   526.005  730000.0  
mass               1.2600     3.040      25.0  
distance          55.2500   178.500    8500.0  
year            2010.0000  2012.000    2014.0

In [903]:
df.dropna().describe().T

count         mean          std        min         25%  \
number          498.0     1.734940     1.175720     1.0000     1.00000   
orbital_period  498.0   835.778671  1469.128259     1.3283    38.27225   
mass            498.0     2.509320     3.636274     0.0036     0.21250   
distance        498.0    52.068213    46.596041     1.3500    24.49750   
year            498.0  2007.377510     4.167284  1989.0000  2005.00000   

                     50%        75%      max  
number             1.000     2.0000      6.0  
orbital_period   357.000   999.6000  17337.5  
mass               1.245     2.8675     25.0  
distance          39.940    59.3325    354.0  
year            2009.000  2011.0000   2014.0

Grouping

In [904]:
df = pd.DataFrame({'gruplar' : ['A','B','C','A','B','C',],
                   'veri'    : [10,124,321,31,8,45]}, columns=['gruplar','veri'])
df

gruplar  veri
0       A    10
1       B   124
2       C   321
3       A    31
4       B     8
5       C    45

In [905]:
df.groupby('gruplar') #aggregation fonksiyonu lazım

In [906]:
df.groupby('gruplar').mean()

veri
gruplar       
A         20.5
B         66.0
C        183.0

In [907]:
df.groupby('gruplar').sum()

veri
gruplar      
A          41
B         132
C         366

In [908]:
df = sns.load_dataset("planets")
df.head()

method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [909]:
df.groupby("method")["orbital_period"].mean()

method
Astrometry                          631.180000
Eclipse Timing Variations          4751.644444
Imaging                          118247.737500
Microlensing                       3153.571429
Orbital Brightness Modulation         0.709307
Pulsar Timing                      7343.021201
Pulsation Timing Variations        1170.000000
Radial Velocity                     823.354680
Transit                              21.102073
Transit Timing Variations            79.783500
Name: orbital_period, dtype: float64

In [910]:
df.groupby("method")["orbital_period"].describe()

count           mean            std  \
method                                                               
Astrometry                       2.0     631.180000     544.217663   
Eclipse Timing Variations        9.0    4751.644444    2499.130945   
Imaging                         12.0  118247.737500  213978.177277   
Microlensing                     7.0    3153.571429    1113.166333   
Orbital Brightness Modulation    3.0       0.709307       0.725493   
Pulsar Timing                    5.0    7343.021201   16313.265573   
Pulsation Timing Variations      1.0    1170.000000            NaN   
Radial Velocity                553.0     823.354680    1454.926210   
Transit                        397.0      21.102073      46.185893   
Transit Timing Variations        3.0      79.783500      71.599884   

                                       min          25%           50%  \
method                                                                  
Astrometry                      246.360000   438.770000    631.180000   
Eclipse Timing Variations      1916.250000  2900.000000   4343.500000   
Imaging                        4639.150000  8343.900000  27500.000000   
Microlensing                   1825.000000  2375.000000   3300.000000   
Orbital Brightness Modulation     0.240104     0.291496      0.342887   
Pulsar Timing                     0.090706    25.262000     66.541900   
Pulsation Timing Variations    1170.000000  1170.000000   1170.000000   
Radial Velocity                   0.736540    38.021000    360.200000   
Transit                           0.355000     3.160630      5.714932   
Transit Timing Variations        22.339500    39.675250     57.011000   

                                        75%            max  
method                                                      
Astrometry                       823.590000    1016.000000  
Eclipse Timing Variations       5767.000000   10220.000000  
Imaging                        94250.000000  730000.000000  
Microlensing                    3550.000000    5100.000000  
Orbital Brightness Modulation      0.943908       1.544929  
Pulsar Timing                     98.211400   36525.000000  
Pulsation Timing Variations     1170.000000    1170.000000  
Radial Velocity                  982.000000   17337.500000  
Transit                           16.145700     331.600590  
Transit Timing Variations        108.505500     160.000000

İLERİ TOPLULAŞTIRMA İŞLEMLERİ
* Aggregate
* Filter
* transform
* apply

In [911]:
df = pd.DataFrame({'gruplar' : ['A','B','C','A','B','C',],
                   'degisken1'    : [10,12,31,12,86,99],
                   'degisken2'    : [20,134,321,313,831,102]}, 
                    columns=['gruplar','degisken1','degisken2'])
df

gruplar  degisken1  degisken2
0       A         10         20
1       B         12        134
2       C         31        321
3       A         12        313
4       B         86        831
5       C         99        102

* aggregate

In [912]:
df.groupby('gruplar').mean()

degisken1  degisken2
gruplar                      
A             11.0      166.5
B             49.0      482.5
C             65.0      211.5

In [913]:
df.groupby('gruplar').aggregate([min, np.median, max])

C:\Users\Giray\AppData\Local\Temp\ipykernel_10472\131899679.py:1: FutureWarning: The provided callable <built-in function min> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  df.groupby('gruplar').aggregate([min, np.median, max])
C:\Users\Giray\AppData\Local\Temp\ipykernel_10472\131899679.py:1: FutureWarning: The provided callable <function median at 0x000001877F5C14E0> is currently using SeriesGroupBy.median. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "median" instead.
  df.groupby('gruplar').aggregate([min, np.median, max])
C:\Users\Giray\AppData\Local\Temp\ipykernel_10472\131899679.py:1: FutureWarning: The provided callable <built-in function max> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass

degisken1            degisken2            
              min median max       min median  max
gruplar                                           
A              10   11.0  12        20  166.5  313
B              12   49.0  86       134  482.5  831
C              31   65.0  99       102  211.5  321

In [914]:
df.groupby('gruplar').aggregate({"degisken1": "min", "degisken2": "max"})

degisken1  degisken2
gruplar                      
A               10        313
B               12        831
C               31        321

In [915]:
df.groupby('gruplar').aggregate({"degisken1": min, "degisken2": max})

C:\Users\Giray\AppData\Local\Temp\ipykernel_10472\959558529.py:1: FutureWarning: The provided callable <built-in function min> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  df.groupby('gruplar').aggregate({"degisken1": min, "degisken2": max})
C:\Users\Giray\AppData\Local\Temp\ipykernel_10472\959558529.py:1: FutureWarning: The provided callable <built-in function max> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  df.groupby('gruplar').aggregate({"degisken1": min, "degisken2": max})


degisken1  degisken2
gruplar                      
A               10        313
B               12        831
C               31        321

* filter

In [916]:
df

gruplar  degisken1  degisken2
0       A         10         20
1       B         12        134
2       C         31        321
3       A         12        313
4       B         86        831
5       C         99        102

In [917]:
def filter_func(x):
    return x["degisken1"].std() > 9

In [918]:
df.groupby("gruplar").std()

degisken1   degisken2
gruplar                       
A         1.414214  207.182287
B        52.325902  492.853426
C        48.083261  154.856385

In [919]:
df.groupby("gruplar").filter(filter_func)

gruplar  degisken1  degisken2
1       B         12        134
2       C         31        321
4       B         86        831
5       C         99        102

* transform

In [920]:
df

gruplar  degisken1  degisken2
0       A         10         20
1       B         12        134
2       C         31        321
3       A         12        313
4       B         86        831
5       C         99        102

In [921]:
df["degisken1"]*9

0     90
1    108
2    279
3    108
4    774
5    891
Name: degisken1, dtype: int64

In [922]:
df_a = df.iloc[:,1:3]
df_a

degisken1  degisken2
0         10         20
1         12        134
2         31        321
3         12        313
4         86        831
5         99        102

In [923]:
df_a.transform(lambda x: x-x.mean())

degisken1   degisken2
0 -31.666667 -266.833333
1 -29.666667 -152.833333
2 -10.666667   34.166667
3 -29.666667   26.166667
4  44.333333  544.166667
5  57.333333 -184.833333

In [924]:
df_a.transform(lambda x: (x-x.mean())/x.std())

degisken1  degisken2
0  -0.785344  -0.913416
1  -0.735743  -0.523174
2  -0.264537   0.116958
3  -0.735743   0.089573
4   1.099481   1.862774
5   1.421886  -0.632716

* apply

In [925]:
df = pd.DataFrame({'degisken1'    : [10,12,31,12,86,99],
                   'degisken2'    : [20,134,321,313,831,102]}, 
                    columns=['degisken1','degisken2'])
df

degisken1  degisken2
0         10         20
1         12        134
2         31        321
3         12        313
4         86        831
5         99        102

In [926]:
df.apply(np.sum)

degisken1     250
degisken2    1721
dtype: int64

In [927]:
df = pd.DataFrame({'gruplar' : ['A','B','C','A','B','C',],
                   'degisken1'    : [10,12,31,12,86,99],
                   'degisken2'    : [20,134,321,313,831,102]}, 
                    columns=['gruplar','degisken1','degisken2'])
df

gruplar  degisken1  degisken2
0       A         10         20
1       B         12        134
2       C         31        321
3       A         12        313
4       B         86        831
5       C         99        102

In [928]:
df.apply(np.sum)

gruplar      ABCABC
degisken1       250
degisken2      1721
dtype: object

In [929]:
df.groupby("gruplar").apply(np.sum)

c:\Users\Giray\AppData\Local\Programs\Python\Python312\Lib\site-packages\numpy\_core\fromnumeric.py:84: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)
c:\Users\Giray\AppData\Local\Programs\Python\Python312\Lib\site-packages\numpy\_core\fromnumeric.py:84: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)
c:\Users\Giray\AppData\Local\Programs\Python\Python312\Lib\site-packages\numpy\_core\fromnumeric.py:84: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the 

gruplar  degisken1  degisken2
gruplar                              
A            AA         22        333
B            BB         98        965
C            CC        130        423

In [930]:
df.groupby("gruplar").apply(np.mean)

gruplar
A     88.75
B    265.75
C    138.25
dtype: float64

# pivot tables

In [931]:
titanic = sns.load_dataset('titanic')
titanic.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [932]:
titanic.groupby('sex')['survived'].mean()

sex
female    0.742038
male      0.188908
Name: survived, dtype: float64

In [933]:
titanic.groupby('sex')[['survived']].mean()

survived
sex             
female  0.742038
male    0.188908

In [934]:
titanic.groupby('sex')[['survived']].sum()

survived
sex             
female       233
male         109

In [935]:
titanic.groupby('sex')['survived'].describe()

count      mean       std  min  25%  50%  75%  max
sex                                                       
female  314.0  0.742038  0.438211  0.0  0.0  1.0  1.0  1.0
male    577.0  0.188908  0.391775  0.0  0.0  0.0  0.0  1.0

In [936]:
titanic.groupby(["sex","class"])[['survived']].aggregate("mean").unstack()

C:\Users\Giray\AppData\Local\Temp\ipykernel_10472\1153637136.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  titanic.groupby(["sex","class"])[['survived']].aggregate("mean").unstack()


survived                    
class      First    Second     Third
sex                                 
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

In [937]:
titanic.groupby(["sex","class"])[['survived']].aggregate("mean")

C:\Users\Giray\AppData\Local\Temp\ipykernel_10472\1189174913.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  titanic.groupby(["sex","class"])[['survived']].aggregate("mean")


survived
sex    class           
female First   0.968085
       Second  0.921053
       Third   0.500000
male   First   0.368852
       Second  0.157407
       Third   0.135447

In [938]:
titanic.groupby(["sex","class","alone"])[['survived']].aggregate("mean").unstack()

C:\Users\Giray\AppData\Local\Temp\ipykernel_10472\2704630183.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  titanic.groupby(["sex","class","alone"])[['survived']].aggregate("mean").unstack()


survived          
alone             False     True 
sex    class                     
female First   0.966667  0.970588
       Second  0.931818  0.906250
       Third   0.416667  0.616667
male   First   0.425532  0.333333
       Second  0.277778  0.097222
       Third   0.180723  0.121212

pivot ile pivot table

In [939]:
titanic.pivot_table("survived", index="sex", columns="class")

C:\Users\Giray\AppData\Local\Temp\ipykernel_10472\774227978.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  titanic.pivot_table("survived", index="sex", columns="class")


class      First    Second     Third
sex                                 
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

In [940]:
titanic.groupby(["sex","class"])[['survived']].aggregate("mean").unstack()

C:\Users\Giray\AppData\Local\Temp\ipykernel_10472\1153637136.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  titanic.groupby(["sex","class"])[['survived']].aggregate("mean").unstack()


survived                    
class      First    Second     Third
sex                                 
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

In [941]:
titanic.age.head()

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
Name: age, dtype: float64

In [942]:
age = pd.cut(titanic["age"], [0, 18, 90])
age.head(20)

0     (18.0, 90.0]
1     (18.0, 90.0]
2     (18.0, 90.0]
3     (18.0, 90.0]
4     (18.0, 90.0]
5              NaN
6     (18.0, 90.0]
7      (0.0, 18.0]
8     (18.0, 90.0]
9      (0.0, 18.0]
10     (0.0, 18.0]
11    (18.0, 90.0]
12    (18.0, 90.0]
13    (18.0, 90.0]
14     (0.0, 18.0]
15    (18.0, 90.0]
16     (0.0, 18.0]
17             NaN
18    (18.0, 90.0]
19             NaN
Name: age, dtype: category
Categories (2, interval[int64, right]): [(0, 18] < (18, 90]]

In [943]:
titanic.pivot_table("survived", ["sex",age], "class")

C:\Users\Giray\AppData\Local\Temp\ipykernel_10472\2298594095.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  titanic.pivot_table("survived", ["sex",age], "class")


class               First    Second     Third
sex    age                                   
female (0, 18]   0.909091  1.000000  0.511628
       (18, 90]  0.972973  0.900000  0.423729
male   (0, 18]   0.800000  0.600000  0.215686
       (18, 90]  0.375000  0.071429  0.133663

# Dış kaynaklı veri okuma işlemleri 

In [944]:
#csv okuma
pd.read_csv("reading_data/ornekcsv.csv", sep= ";")

a    b     c
0    78   12   1.0
1    78   12   2.0
2    78  324   3.0
3     7    2   4.0
4    88   23   5.0
5     6    2   NaN
6    56   11   6.0
7     7   12   7.0
8    56   21   7.0
9   346    2   8.0
10    5    1   8.0
11  456   21   8.0
12    3   12  88.0

In [945]:
?pd.read_csv

Signature:
pd.read_csv(
    filepath_or_buffer: 'FilePath | ReadCsvBuffer[bytes] | ReadCsvBuffer[str]',
    *,
    sep: 'str | None | lib.NoDefault' = <no_default>,
    delimiter: 'str | None | lib.NoDefault' = None,
    header: "int | Sequence[int] | None | Literal['infer']" = 'infer',
    names: 'Sequence[Hashable] | None | lib.NoDefault' = <no_default>,
    index_col: 'IndexLabel | Literal[False] | None' = None,
    usecols: 'UsecolsArgType' = None,
    dtype: 'DtypeArg | None' = None,
    engine: 'CSVEngine | None' = None,
    converters: 'Mapping[Hashable, Callable] | None' = None,
    true_values: 'list | None' = None,
    false_values: 'list | None' = None,
    skipinitialspace: 'bool' = False,
    skiprows: 'list[int] | int | Callable[[Hashable], bool] | None' = None,
    skipfooter: 'int' = 0,
    nrows: 'int | None' = None,
    na_values: 'Hashable | Iterable[Hashable] | Mapping[Hashable, Iterable[Hashable]] | None' = None,
    keep_default_na: 'bool' = True,
    na_filter: '

In [946]:
#txt okuma
pd.read_csv("reading_data/duz_metin.txt")

1 2
0   2 2
1   3 2
2   4 2
3   5 2
4   6 2
5  7 2 
6   8 2
7   9 2
8  10 2

In [947]:
#excel
pd.read_excel("reading_data/ornekx.xlsx")

a    b     c
0    78   12   1.0
1    78   12   2.0
2    78  324   3.0
3     7    2   4.0
4    88   23   5.0
5     6    2   NaN
6    56   11   6.0
7     7   12   7.0
8    56   21   7.0
9   346    2   8.0
10    5    1   8.0
11  456   21   8.0
12    3   12  88.0

In [948]:
df = pd.read_excel("reading_data/ornekx.xlsx")
df

a    b     c
0    78   12   1.0
1    78   12   2.0
2    78  324   3.0
3     7    2   4.0
4    88   23   5.0
5     6    2   NaN
6    56   11   6.0
7     7   12   7.0
8    56   21   7.0
9   346    2   8.0
10    5    1   8.0
11  456   21   8.0
12    3   12  88.0

In [949]:
df.head()

a    b    c
0  78   12  1.0
1  78   12  2.0
2  78  324  3.0
3   7    2  4.0
4  88   23  5.0

In [950]:
df.columns = ("A","B","C")
df

A    B     C
0    78   12   1.0
1    78   12   2.0
2    78  324   3.0
3     7    2   4.0
4    88   23   5.0
5     6    2   NaN
6    56   11   6.0
7     7   12   7.0
8    56   21   7.0
9   346    2   8.0
10    5    1   8.0
11  456   21   8.0
12    3   12  88.0

In [951]:
m = np.random.randint(1,30, size = (10,3))
df = pd.DataFrame(m, columns = ["var1","var2","var3"])

In [952]:
df.var1

0    16
1    28
2     4
3    14
4     7
5    15
6    23
7     8
8     2
9    19
Name: var1, dtype: int32

In [953]:
df["var1"]

0    16
1    28
2     4
3    14
4     7
5    15
6    23
7     8
8     2
9    19
Name: var1, dtype: int32

In [954]:
df.values

array([[16,  2, 29],
       [28, 14, 29],
       [ 4, 16,  1],
       [14, 26, 21],
       [ 7,  6, 24],
       [15,  4, 22],
       [23,  8,  6],
       [ 8,  2, 25],
       [ 2,  3, 12],
       [19, 10,  8]], dtype=int32)

In [956]:
df = pd.DataFrame({'gruplar' : ['A','B','C','A','B','C',],
                   'degisken1'    : [10,12,31,12,86,99],
                   'degisken2'    : [20,134,321,313,831,102]}, 
                    columns=['gruplar','degisken1','degisken2'])
df

gruplar  degisken1  degisken2
0       A         10         20
1       B         12        134
2       C         31        321
3       A         12        313
4       B         86        831
5       C         99        102

In [958]:
df.groupby("gruplar").mean()

degisken1  degisken2
gruplar                      
A             11.0      166.5
B             49.0      482.5
C             65.0      211.5

In [959]:
seri = pd.Series([121,200,150,99])

seri.values

array([121, 200, 150,  99])